_wandb:
    value:
        cli_version: 0.21.4
        e:
            620bbosps9yvccrhs6oisrvjzkeoeayt:
                codePath: train.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "255508611072"
                        used: "190614499328"
                email: okwhere25@gmail.com
                executable: /home/w-ok-e/Documents/ELiTNet/.venv/bin/python3
                git:
                    commit: 3698cda09adae00de79a8e3a0d90e0b31f581612
                    remote: https://github.com/dipayandewan94/ELiTNet.git
                gpu: NVIDIA GeForce RTX 2050
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 2050
                      uuid: GPU-f14ca48a-b448-8e48-da89-dc71528a5ade
                host: woke-Aspire-A715-79G
                memory:
                    total: "16442089472"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.35
                program: /home/w-ok-e/Documents/ELiTNet/train.py
                python: CPython 3.10.12
                root: /home/w-ok-e/Documents/ELiTNet
                startedAt: "2025-09-15T14:48:00.131475Z"
                writerId: 620bbosps9yvccrhs6oisrvjzkeoeayt
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 9
                - 50
                - 80
                - 103
            "2":
                - 1
                - 9
                - 50
                - 80
                - 103
            "3":
                - 7
                - 13
                - 14
                - 16
                - 66
            "4": 3.10.12
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
dataset:
    value:
        class_names:
            - EX
            - HE
            - MA
            - OD
            - SE
        global_batch_size: 2
        ignore_index: 0
        img_size: 512
        name: IDRiD
        num_channels: 3
        num_classes: 5
        test_dataset:
            _partial_: false
            _target_: data.data.IDRiD
            root_dir: /home/w-ok-e/Documents/ELiTNet/datasets/IDRiD/
            split: test
        train_dataset:
            _partial_: false
            _target_: data.data.IDRiD
            root_dir: /home/w-ok-e/Documents/ELiTNet/datasets/IDRiD/
            split: train
        val_dataset:
            _partial_: false
            _target_: data.data.IDRiD
            root_dir: /home/w-ok-e/Documents/ELiTNet/datasets/IDRiD/
            split: val
model:
    value:
        loss:
            instance:
                _target_: torch.nn.CrossEntropyLoss
                ignore_index: 0
        lr_scheduler:
            _partial_: true
            _target_: utils.lr_scheduler.WarmupLR
            warmup_steps: 500
        name: ELiTNet
        network:
            instance:
                _target_: models.network.ElitNet.ElitNet
                conv_bridge: true
                in_channels: 3
                kernel_sz: 3
                layers:
                    - 4
                    - 8
                    - 16
                num_classes: 2
                shortcut: true
                up_mode: up_conv
        optimizer:
            exclude_bias_from_wd: true
            optim:
                _target_: torch.optim.Adam
                lr: 0.002
                weight_decay: 1e-05
        test_metrics:
            _target_: metrics.seg_metrics.SegmentationMetrics
            class_names:
                - EX
                - HE
                - MA
                - OD
                - SE
            ignore_index: 0
            num_classes: 5
        train_metrics:
            _target_: metrics.seg_metrics.SegmentationMetrics
            class_names:
                - EX
                - HE
                - MA
                - OD
                - SE
            ignore_index: 0
            num_classes: 5
        val_metrics:
            _target_: metrics.seg_metrics.SegmentationMetrics
            class_names:
                - EX
                - HE
                - MA
                - OD
                - SE
            ignore_index: 0
            num_classes: 5
