name: DRIVE
global_batch_size: 2
img_size: 512
num_channels: 3
num_classes: 2
ignore_index: 0
class_names: ["background", "vessel"]

train_dataset:
  _partial_: false
  _target_: data.data.DRIVE
  root_dir: ${data_dir}/DRIVE/
  split: train
  train_length: 20
  aug_range: 2

val_dataset:
  _partial_: false
  _target_: data.data.DRIVE
  root_dir: ${data_dir}/DRIVE/
  split: val

test_dataset:
  _partial_: false
  _target_: data.data.DRIVE
  root_dir: ${data_dir}/DRIVE/
  split: test
